#ifndef SYSTEM_PLUGIN_COMMON_H
#define SYSTEM_PLUGIN_COMMON_H

#define PLUGIN_NAME "system-plugin"

#define BASE_YANG_MODEL "ietf-system"

#define SYSTEM_SYSTEM_CONTAINER_YANG_PATH "/" BASE_YANG_MODEL ":system"

#define SYSTEM_HOSTNAME_YANG_PATH SYSTEM_SYSTEM_CONTAINER_YANG_PATH "/hostname"

#endif // SYSTEM_PLUGIN_COMMON_H