#ifndef SYSTEM_PLUGIN_COMMON_H
#define SYSTEM_PLUGIN_COMMON_H

#define PLUGIN_NAME "system-plugin"

#define BASE_YANG_MODEL "ietf-system"

#define SYSTEM_SYSTEM_CONTAINER_YANG_PATH "/" BASE_YANG_MODEL ":system"

#define SYSTEM_CONTACT_YANG_PATH SYSTEM_SYSTEM_CONTAINER_YANG_PATH "/contact"
#define SYSTEM_HOSTNAME_YANG_PATH SYSTEM_SYSTEM_CONTAINER_YANG_PATH "/hostname"
#define SYSTEM_LOCATION_YANG_PATH SYSTEM_SYSTEM_CONTAINER_YANG_PATH "/location"

#define SYSTEM_TIMEZONE_NAME_YANG_PATH SYSTEM_SYSTEM_CONTAINER_YANG_PATH "/clock/timezone-name"
#define SYSTEM_TIMEZONE_UTC_OFFSET_YANG_PATH SYSTEM_SYSTEM_CONTAINER_YANG_PATH "/clock/timezone-utc-offset"

#define SYSTEM_NTP_ENABLED_YANG_PATH SYSTEM_SYSTEM_CONTAINER_YANG_PATH "/ntp/enabled"
#define SYSTEM_NTP_SERVER_YANG_PATH SYSTEM_SYSTEM_CONTAINER_YANG_PATH "/ntp/server"

#define SYSTEM_DNS_RESOLVER_SEARCH_YANG_PATH SYSTEM_SYSTEM_CONTAINER_YANG_PATH "/dns-resolver/search"
#define SYSTEM_DNS_RESOLVER_SERVER_YANG_PATH SYSTEM_SYSTEM_CONTAINER_YANG_PATH "/dns-resolver/server"
#define SYSTEM_DNS_RESOLVER_TIMEOUT_YANG_PATH SYSTEM_SYSTEM_CONTAINER_YANG_PATH "/dns-resolver/options/timeout"
#define SYSTEM_DNS_RESOLVER_ATTEMPTS_YANG_PATH SYSTEM_SYSTEM_CONTAINER_YANG_PATH "/dns-resolver/options/attempts"

#define SYSTEM_AUTHENTICATION_USER_AUTHENTICATION_ORDER_YANG_PATH SYSTEM_SYSTEM_CONTAINER_YANG_PATH "/authentication/user-authentication-order"
#define SYSTEM_AUTHENTICATION_USER_YANG_PATH SYSTEM_SYSTEM_CONTAINER_YANG_PATH "/authentication/user"

#endif // SYSTEM_PLUGIN_COMMON_H